### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [usnistgov/pycdcs#1]
Could you please tag the source? This allows distributions to get the complete source from GitHub.

Thanks

**Comment by lmhale99** [comment]
Is there a particular place for tagging it?  The setup.py has a url field pointing to this repository.  Do you want me to add the download_url field as well? Or somewhere else?

**Comment by fabaff** [comment]
To build the package for NixOS and other distributions, tagging is enough.

E.g., 

```bash
git tag -a 0.1.2 && git push origin 0.1.2
```

**Comment by lmhale99** [comment]
Ok, I see. I just missed the last v0.1.6 tag.  It has been added to the repo now.

**Comment by fabaff** [comment]
0.1.9 is missing again.
